DROP DATABASE IF EXISTS employee_tracker;
CREATE DATABASE employee_tracker;

USE employee_tracker;
CREATE TABLE department(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(30) NOT NULL,
)

CREATE TABLE role(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INTEGER NOT NULL,
  CONSTRAINT department_frk FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE CASCADE
)

CREATE TABLE employee(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  role_id INTEGER NOT NULL,
  CONSTRAINT role_frk FOREIGN KEY (role_id) REFERENCES role(id) ON DELETE CASCADE
  manager_id INTEGER NOT NULL,
  CONSTRAINT manager_frk FOREIGN KEY (manager_id) REFERENCES employee(id) ON DELETE SET NULL
)